### PR TITLE
GEN-454 - Upgrade Unleash to 4.4.4

### PR DESCRIPTION
**Pull request by KyleBanks**

### CODE REVIEW

**Review by TheMightyGit — APPROVED** [review]
I don't know npm well enough to say if the package.json looks good. Docker looks fine tho :)

**Comment by poblish** [comment]
No reason to think this isn't fine 👍 

If it was me I might have just kept the Old World versions as close as possible to what's proven in Prod in order to avoid any API incompatibilities between versions 3 and 4, which I believe are unknown. Yes, that's doable, that's testable, but the advantage of having the OW and NW running in parallel with two distinct sets of versions is that all the onus is on NW to prove itself against the existing tests without impacting on Prod, but hopefully killing multiple birds with the same stone when tests pass. But feel free to bring the worlds together any way you like, you've probably put more thought into that area.

**Review by poblish — APPROVED** [review]

**Comment by poblish** [comment]
BTW I haven't looked in detail to see why this fork was needed, how it has evolved since the original 3.6.0 - but if it's some tweaks specific to us, shouldn't we pull the upstream https://github.com/Unleash/unleash-docker/tree/4.4.4 and layer those on top, rather than go further down the rabbit hole? Perhaps not relevant if this will be obsolete in New World.

**Comment by conclusionlogic** [comment]
This Unleash fork was needed only to override the internal port so that Goat could deploy Unleash.
Goat expects every service to run on HTTP port 80 so that it could expose anything from 30000-32767 range to 80 of the containerised app.

**Comment by conclusionlogic** [comment]
More info on the requirements here:
https://bitbucket.glintpay.com/projects/GDEP/repos/goat/browse/doc

**Comment by conclusionlogic** [comment]
And those are the changes I had to introduce to Unleash for it to be deployable with Goat:
https://github.com/GlintPay/unleash-docker/commit/565e37f7d197eab36309bc57820ec936de1273fc
https://github.com/GlintPay/unleash-docker/commit/5c6ff575bc788c54aa18892fba70d8d87e7b9db9

**Pull request merged**
